name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lftp openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SFTP (mirror)
        run: |
          LOCALDIR=$(pwd)
          REMOTEDIR="${{ secrets.REMOTE_PROD_PROJECT_FOLDER_PATH }}"

          lftp sftp://${{ secrets.SFTP_PROD_USERNAME }}:${{ secrets.SFTP_PROD_PWD }}@${{ secrets.REMOTE_HOST }} -e "
            set sftp:auto-confirm yes;
            set net:timeout 300;
            set net:max-retries 3;
            cd $REMOTEDIR;
            mirror -R -v --only-newer --delete \
              --exclude .env/ \
              --exclude media/ \
              --exclude .git/ \
              --exclude .github/ \
              --exclude node_modules/ \
              $LOCALDIR/ ./
            quit
          "

      - name: Remote SSH - Build and Restart containers
        run: |
          SSH_USER=${{ secrets.SFTP_PROD_USERNAME }}
          SSH_HOST=${{ secrets.REMOTE_HOST }}
          APP_DIR=${{ secrets.REMOTE_PROD_PROJECT_FOLDER_PATH }}

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            cd "$APP_DIR"
            cp .env.example .env
            sed -i 's#^DATABASE_URI=.*#DATABASE_URI=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}#' .env
            sed -i 's#^PAYLOAD_SECRET=.*#PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}#' .env
            sed -i 's#^PAYLOAD_PREVIEW_SECRET=.*#PAYLOAD_PREVIEW_SECRET=${{ secrets.PAYLOAD_PREVIEW_SECRET }}#' .env
            sed -i 's#^NEXT_PUBLIC_CMS_URL=.*#NEXT_PUBLIC_CMS_URL=${{ secrets.NEXT_PUBLIC_CMS_URL }}#' .env
            sed -i 's#^POSTGRES_DB=.*#POSTGRES_DB=${{ secrets.POSTGRES_DB }}#' .env
            sed -i 's#^POSTGRES_USER=.*#POSTGRES_USER=${{ secrets.POSTGRES_USER }}#' .env
            sed -i 's#^POSTGRES_PASSWORD=.*#POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}#' .env
            sed -i 's#^PGADMIN_DEFAULT_EMAIL=.*#PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}#' .env
            sed -i 's#^PGADMIN_DEFAULT_PASSWORD=.*#PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_PASSWORD }}#' .env
            sed -i 's#^NODE_ENV=.*#NODE_ENV=${{ secrets.NODE_ENV }}#' .env
            docker compose down
            docker compose build
            docker compose up -d
          EOF
